---
id: sam
name: Sam
full: Anti-spam user preferences application
description: >
  Sam allows each user to change their specific anti-spam rules for
  SpamAssassion or Amavisd-new, given a general subset of the overall features
  that are available.
list: horde
type: application
